### ISSUE TITLE
Is this package unmaintained?

### ISSUE THREAD

**Issue by ndelangen** [lukeapage/node-markdown-spellcheck#100]
This is actually a very useful package.

Sadly it seems it's no longer maintained. Is any of the forks interested in taking over this project?

@evanread @orta @rangle @alanthai @streeter @ColinEberhardt @lukeapage 

The easy at which this tool does local dictionaries I have not found anywhere else.

How can we keep this package up and secure?

**Comment by ColinEberhardt** [comment]
You're right, it is useful! Are there specific issues or pull requests that you think need attention? Most of the PRs I can see are just greenkeeper 'noise'

**Comment by ndelangen** [comment]
It's not entirely noise:
https://david-dm.org/lukeapage/node-markdown-spellcheck

I am interested in using it for linting documentation for [Storybook](https://github.com/storybooks/storybook), however I do not want to introduce a package that's insecure and unmaintained you see?

**Comment by evanread** [comment]
It's convenient for those of us using Node projects, but there are other ways to get access to the dictionaries.

The cli tools themselves need work - the parser is easily fooled.

I don't currently want to maintain the project. If pushed, I'd probably find an alternative. My fork was for: https://github.com/lukeapage/node-markdown-spellcheck/pull/97

**Comment by lukeapage** [comment]
Hi,
Sorry I seem to have missed the issues.. I am merging and replying. I'm happy to do minor things but I am unlikely to be fixing random bugs.
