### ISSUE TITLE
Combine summary and report 

### ISSUE THREAD

**Issue by ColinEberhardt** [lukeapage/node-markdown-spellcheck#37]
Just a heads-up as to what I started working on - within the grunt task I started implementing an output that looks very much like the output you get from running JSHint through grunt.

However, I've started moving this code back into the mdspell tool itself. I'm proposing removing the 'summary' option and having `mdspell -r` output the formatted report.

I plan to implement it in such a way that the same report can easily be generated within the grunt task, so potentially exposing a few more bits and pieces from `index.js`. 

I'll probably do a bit more work on this tonight on the train home. If you've got any thoughts / ideas, let me know.

**Comment by lukeapage** [comment]
> However, I've started moving this code back into the mdspell tool itself. I'm proposing removing the 'summary' option and having mdspell -r output the formatted report.

fine

> I plan to implement it in such a way that the same report can easily be generated within the grunt task, so potentially exposing a few more bits and pieces from index.js.

yep.. One conflict is I started working on seperating cli.js into `multi-file-processor.js` `cli-interactive.js` and `cli.js`. Its not perfect but I pushed a WIP to 

https://github.com/lukeapage/node-markdown-spellcheck/tree/refactor

its mostly tidying up left to do.. so I would base your work on that?

**Comment by lukeapage** [comment]
other things that occurred to me was at some point my classes should use instances instead of being static - its a bit debilitating that it couldn't process 2 files at once at the moment.

**Comment by ColinEberhardt** [comment]
>  Its not perfect but I pushed a WIP to ...

Thanks for letting me know, shouldn't effect me much, the report formatting logic lives outside of `cli`
