### ISSUE TITLE
How can I escape the `#` in `.spelling`?

### ISSUE THREAD

**Issue by kvz** [lukeapage/node-markdown-spellcheck#40]
Thanks a lot for this project!

I'm adding this to our CI setup and will write up a post about it on the Transloadit's company blog.

I'd like to silence warnings about a few snippets of code in my markdown, and hence am trying to add something to `.spelling` that starts with a `#`

To illustrate, a small screenshot:

<img width="424" alt="screen shot 2015-09-12 at 15 21 09" src="https://cloud.githubusercontent.com/assets/26752/9831734/8010fdec-5962-11e5-99aa-2ecf0a4df2f1.png">

I've tried adding `\#upload-form` and `\\#upload-form` as well but that didn't help

**Comment by lukeapage** [comment]
Thanks, we do need to be able to escape # but out of interest are you surrounding the code block in anything?
We currently ignore code blocks we can recognise.

**Comment by lukeapage** [comment]
I've corrected the code to not include the `#` in the spelling
