### ISSUE TITLE
Some words not in the US dictionary

### ISSUE THREAD

**Issue by kvz** [lukeapage/node-markdown-spellcheck#44]
Not critical as I could easily add them to `.spelling`. Also some of these are probably disputable (note I'm not a native English speaker, and not sure if company names and abbreviations would even be considered) but I would have expected some in this list:

 - internet
 - spammers
 - handhelds
 - smartphone
 - firewalling
 - terabyte
 - inbox
 - playlist
 - Google
 - blog
 - screenshot
 - e.g.
 - versioning
 - online
 - html
 - interoperable
 - iPad
 - versioned
 - hoodies
 - virtualization
 - checkbox
 - fallback
 - usernames
 - indices

**Comment by lukeapage** [comment]
I need to search around for better American English hunspell dictionaries..

**Comment by kvz** [comment]
Ironically, it also doesn't know `misspelt` :smile:

**Comment by lukeapage** [comment]
I was using a very outdated US dictionary. I will release an update soon.

I've raised the words still missing here - https://github.com/kevina/wordlist/issues/125 apart from `firewalling` which I wasn't sure was valid. That seems to be the best US dictionary I can find (I will use en-us-large - en-us doesn't include interoperable)

**Comment by lukeapage** [comment]
published 0.6.2

**Comment by kvz** [comment]
Great!

Words that I had expected in this:

- resize
- filename(s)
- checksum
- (status ) quo
- installable

But that's all I got - and these are pretty IT specific so seems like a big improvement!

**Comment by lukeapage** [comment]
Feel free to raise those with the relevant dictionary - https://github.com/lukeapage/node-markdown-spellcheck#dictionaries-being-used

**Comment by kvz** [comment]
Okay done https://github.com/kevina/wordlist/issues/126 !
