### ISSUE TITLE
including the spanish language?

### ISSUE THREAD

**Issue by gaboesquivel** [lukeapage/node-markdown-spellcheck#50]
Hi @lukeapage, are you interested in adding spanish ?
I'm have it ready for es5 version on [this brach](https://github.com/gaboesquivel/node-markdown-spellcheck/tree/spanish) ... I'm using it for spell-checking this gitbook we're starting to write [CostaRicaJS/Fundamentos-de-JavaScript](https://github.com/CostaRicaJS/Fundamentos-de-JavaScript/)

**Comment by lukeapage** [comment]
yes, make a PR, thanks
